/*
Navicat SQL Server Data Transfer

Source Server         : LAPTOP-60GQO6T2
Source Server Version : 110000
Source Host           : LAPTOP-60GQO6T2:1433
Source Database       : GrisGris
Source Schema         : dbo

Target Server Type    : SQL Server
Target Server Version : 110000
File Encoding         : 65001

Date: 2017-02-04 18:59:04
*/


-- ----------------------------
-- Table structure for SERVICIOSPORPROFESIONAL
-- ----------------------------
DROP TABLE [dbo].[SERVICIOSPORPROFESIONAL]
GO
CREATE TABLE [dbo].[SERVICIOSPORPROFESIONAL] (
[IDSERXPROFESIONAL] int NOT NULL IDENTITY(1,1) ,
[IDPROFESIONAL] int NULL ,
[IDSERVICIO] int NULL 
)


GO
DBCC CHECKIDENT(N'[dbo].[SERVICIOSPORPROFESIONAL]', RESEED, 23)
GO

-- ----------------------------
-- Records of SERVICIOSPORPROFESIONAL
-- ----------------------------
SET IDENTITY_INSERT [dbo].[SERVICIOSPORPROFESIONAL] ON
GO
INSERT INTO [dbo].[SERVICIOSPORPROFESIONAL] ([IDSERXPROFESIONAL], [IDPROFESIONAL], [IDSERVICIO]) VALUES (N'1', N'1', N'1')
GO
GO
INSERT INTO [dbo].[SERVICIOSPORPROFESIONAL] ([IDSERXPROFESIONAL], [IDPROFESIONAL], [IDSERVICIO]) VALUES (N'2', N'1', N'3')
GO
GO
INSERT INTO [dbo].[SERVICIOSPORPROFESIONAL] ([IDSERXPROFESIONAL], [IDPROFESIONAL], [IDSERVICIO]) VALUES (N'3', N'1', N'4')
GO
GO
INSERT INTO [dbo].[SERVICIOSPORPROFESIONAL] ([IDSERXPROFESIONAL], [IDPROFESIONAL], [IDSERVICIO]) VALUES (N'4', N'1', N'8')
GO
GO
INSERT INTO [dbo].[SERVICIOSPORPROFESIONAL] ([IDSERXPROFESIONAL], [IDPROFESIONAL], [IDSERVICIO]) VALUES (N'5', N'1', N'10')
GO
GO
INSERT INTO [dbo].[SERVICIOSPORPROFESIONAL] ([IDSERXPROFESIONAL], [IDPROFESIONAL], [IDSERVICIO]) VALUES (N'6', N'1', N'11')
GO
GO
INSERT INTO [dbo].[SERVICIOSPORPROFESIONAL] ([IDSERXPROFESIONAL], [IDPROFESIONAL], [IDSERVICIO]) VALUES (N'7', N'1', N'12')
GO
GO
INSERT INTO [dbo].[SERVICIOSPORPROFESIONAL] ([IDSERXPROFESIONAL], [IDPROFESIONAL], [IDSERVICIO]) VALUES (N'8', N'1', N'13')
GO
GO
INSERT INTO [dbo].[SERVICIOSPORPROFESIONAL] ([IDSERXPROFESIONAL], [IDPROFESIONAL], [IDSERVICIO]) VALUES (N'9', N'1', N'14')
GO
GO
INSERT INTO [dbo].[SERVICIOSPORPROFESIONAL] ([IDSERXPROFESIONAL], [IDPROFESIONAL], [IDSERVICIO]) VALUES (N'10', N'1', N'17')
GO
GO
INSERT INTO [dbo].[SERVICIOSPORPROFESIONAL] ([IDSERXPROFESIONAL], [IDPROFESIONAL], [IDSERVICIO]) VALUES (N'11', N'2', N'1')
GO
GO
INSERT INTO [dbo].[SERVICIOSPORPROFESIONAL] ([IDSERXPROFESIONAL], [IDPROFESIONAL], [IDSERVICIO]) VALUES (N'12', N'2', N'3')
GO
GO
INSERT INTO [dbo].[SERVICIOSPORPROFESIONAL] ([IDSERXPROFESIONAL], [IDPROFESIONAL], [IDSERVICIO]) VALUES (N'13', N'2', N'4')
GO
GO
INSERT INTO [dbo].[SERVICIOSPORPROFESIONAL] ([IDSERXPROFESIONAL], [IDPROFESIONAL], [IDSERVICIO]) VALUES (N'14', N'3', N'1')
GO
GO
INSERT INTO [dbo].[SERVICIOSPORPROFESIONAL] ([IDSERXPROFESIONAL], [IDPROFESIONAL], [IDSERVICIO]) VALUES (N'15', N'3', N'2')
GO
GO
INSERT INTO [dbo].[SERVICIOSPORPROFESIONAL] ([IDSERXPROFESIONAL], [IDPROFESIONAL], [IDSERVICIO]) VALUES (N'16', N'3', N'5')
GO
GO
INSERT INTO [dbo].[SERVICIOSPORPROFESIONAL] ([IDSERXPROFESIONAL], [IDPROFESIONAL], [IDSERVICIO]) VALUES (N'17', N'3', N'6')
GO
GO
INSERT INTO [dbo].[SERVICIOSPORPROFESIONAL] ([IDSERXPROFESIONAL], [IDPROFESIONAL], [IDSERVICIO]) VALUES (N'18', N'3', N'7')
GO
GO
INSERT INTO [dbo].[SERVICIOSPORPROFESIONAL] ([IDSERXPROFESIONAL], [IDPROFESIONAL], [IDSERVICIO]) VALUES (N'19', N'3', N'8')
GO
GO
INSERT INTO [dbo].[SERVICIOSPORPROFESIONAL] ([IDSERXPROFESIONAL], [IDPROFESIONAL], [IDSERVICIO]) VALUES (N'20', N'3', N'9')
GO
GO
INSERT INTO [dbo].[SERVICIOSPORPROFESIONAL] ([IDSERXPROFESIONAL], [IDPROFESIONAL], [IDSERVICIO]) VALUES (N'21', N'3', N'10')
GO
GO
INSERT INTO [dbo].[SERVICIOSPORPROFESIONAL] ([IDSERXPROFESIONAL], [IDPROFESIONAL], [IDSERVICIO]) VALUES (N'22', N'3', N'15')
GO
GO
INSERT INTO [dbo].[SERVICIOSPORPROFESIONAL] ([IDSERXPROFESIONAL], [IDPROFESIONAL], [IDSERVICIO]) VALUES (N'23', N'3', N'16')
GO
GO
SET IDENTITY_INSERT [dbo].[SERVICIOSPORPROFESIONAL] OFF
GO

-- ----------------------------
-- Indexes structure for table SERVICIOSPORPROFESIONAL
-- ----------------------------
CREATE INDEX [RELACIONSERVICIOPORPROFESIONAL_FK] ON [dbo].[SERVICIOSPORPROFESIONAL]
([IDSERVICIO] ASC) 
GO
CREATE INDEX [OTRARELACION_FK] ON [dbo].[SERVICIOSPORPROFESIONAL]
([IDPROFESIONAL] ASC) 
GO

-- ----------------------------
-- Primary Key structure for table SERVICIOSPORPROFESIONAL
-- ----------------------------
ALTER TABLE [dbo].[SERVICIOSPORPROFESIONAL] ADD PRIMARY KEY ([IDSERXPROFESIONAL])
GO

-- ----------------------------
-- Foreign Key structure for table [dbo].[SERVICIOSPORPROFESIONAL]
-- ----------------------------
ALTER TABLE [dbo].[SERVICIOSPORPROFESIONAL] ADD FOREIGN KEY ([IDPROFESIONAL]) REFERENCES [dbo].[PROFESIONAL] ([IDPROFESIONAL]) ON DELETE NO ACTION ON UPDATE NO ACTION
GO
ALTER TABLE [dbo].[SERVICIOSPORPROFESIONAL] ADD FOREIGN KEY ([IDSERVICIO]) REFERENCES [dbo].[SERVICIO] ([IDSERVICIO]) ON DELETE NO ACTION ON UPDATE NO ACTION
GO
